# Generated by Django 2.2 on 2020-12-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201220_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='writer',
            field=models.CharField(default='', max_length=100),
        ),
    ]
