# Generated by Django 2.2 on 2020-12-20 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201220_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pdf',
        ),
    ]
